volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: macmillan1411/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
    networks:
      - proxy-net

  frontend:
    image: macmillan1411/taski_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - proxy-net

  gateway:
    image: macmillan1411/taski_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
    depends_on:
      - backend
      - frontend
    environment:
      - VIRTUAL_HOST=taski.gudoprojects.ru
      - LETSENCRYPT_HOST=taski.gudoprojects.ru
      - LETSENCRYPT_EMAIL=your@email.com
    expose:
      - "80"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true









